name: Scheduled Report

on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 13 * * *'
    - cron: '0 20 * * *'

jobs:
  call-report:
    runs-on: ubuntu-latest

    steps:
      - name: Call Report API
        run: curl https://metals-dashboard-oxwz.vercel.app/api/scheduled-report