name: Scheduled Report

on:
  schedule:
    - cron: '0 6 * * *'   # 09:00 Tehran
    - cron: '0 13 * * *'  # 16:00 Tehran
    - cron: '0 20 * * *'  # 23:00 Tehran
  workflow_dispatch:

jobs:
  call-report:
    runs-on: ubuntu-latest

    steps:
      - name: Call Report API
        run: |
          curl -X GET https://metals-dashboard-oxwz.vercel.app/api/scheduled-report